### ISSUE TITLE
Trying to understand you're binning

### ISSUE THREAD

**Issue by mramos-stellar** [rsquaredacademy/rfm#17]
At one point, I used default bins for frequency and for my test data it only returned 2 bins, 1 and 5. 

My own implementation, I'm using quintiles, but in your function, how are you computing your bins?

**Comment by aravindhebbali** [comment]
hi @mramos-stellar, we use the `quantile()` function for binning. Refer to the `bins()` function [here](https://github.com/rsquaredacademy/rfm/blob/master/R/utils.R).

**Comment by aravindhebbali** [comment]
Looks like `ntile()` will return bins of equal width. Using it in our case will group customers with different values in the same bin, giving them the same score even though they might have very different values and should have different scores.

**Comment by mramos-stellar** [comment]
Thanks for the feedback. However, with my example earlier, I would then now have just 2 bins instead of 5. Because of the value thereby giving customers a score of good or worst only. 

I was following the guidance though from [rfm analysis](https://www.putler.com/rfm-analysis/) on my understand of their description of quintiles.

But thanks again and this is a great package and I learned a lot.

**Comment by aravindhebbali** [comment]
I have followed the approach used by [SPSS](http://www.sussex.ac.uk/its/pdfs/SPSS_Direct_Marketing_22.pdf) and that is why we are observing the difference in the scores. Another case where the scores differ are when the values are skewed. Thanks for your inputs and am glad you liked the package.
