### ISSUE TITLE
Champions and Others

### ISSUE THREAD

**Issue by IeUDE** [rsquaredacademy/rfm#56]
Hello,

first I would like to thank you for this great package. I have been using in a project of mine and been working wonders, again thank you!

I have an issue or like a question, since it also pops up in your guide to 'rfm': https://rfm.rsquaredacademy.com/articles/rfm-customer-level-data.html#segments

Where are the 'Champions' in your guide/data ... ?
 - Don't we here have cases where they should pop up?
- I mean, we have a lot of cases where of 3 x 4-5 and very high RFM scores and low recency, should these not be even better than "Loyal Customers" ...
- What am I missing here?

And how are the 'Others' generated?
 - I guess, are cases that do not match any of the other segments, right?

Thank you.

**Comment by aravindhebbali** [comment]
hi @IeUDE 

It depends on how you define the intervals for the individual scores. I have defined better interval in the below blog post where you can see the Champion customers:

https://blog.rsquaredacademy.com/customer-segmentation-using-rfm-analysis/

In the vignette, the intervals defined for recency, frequency & monetary for the Champion segment are a subset of the intervals defined for Loyal Customer segment and hence you do not see Champion customers in the output.

Customers get classified into the Others segment when they do not fall into any of the segments defined. To avoid that, the intervals for recency, frequency & monetary have to be exhaustive.
